development:
  adapter: postgresql
  database: orderbuddy_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: orderbuddy_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: orderbuddy_production
  pool: 5
  timeout: 5000