default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
  username: orderbuddy
  password: a 

development:
  <<: *default
  database: orderbuddy_development

test:
  <<: *default
  database: orderbuddy_test

production:
  <<: *default
  database: orderbuddy_production